language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 app_namespace
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
